use_frameworks!
inhibit_all_warnings!

# version = '3.0.0'
version = '~> 3.0'

target 'iOS Example' do
  platform :ios, '9.0'
end

target 'BackgroundRealm_iOS' do
  platform :ios, '9.0'
  
  pod 'RealmSwift', version
  
  target 'iOS Tests' do
      inherit! :search_paths
  end
end

target 'BackgroundRealm_watchOS' do
    platform :watchos, '3.0'
    
    pod 'RealmSwift', version
end

target 'tvOS Example' do
    platform :tvos, '10.0'
end

target 'BackgroundRealm_tvOS' do
    platform :tvos, '10.0'
    
    pod 'RealmSwift', version
    
    target 'tvOS Tests' do
        inherit! :search_paths
    end
end

target 'macOS Example' do
    platform :osx, '10.10'
end

target 'BackgroundRealm_macOS' do
    platform :osx, '10.10'
    
    pod 'RealmSwift', version
    
    target 'macOS Tests' do
        inherit! :search_paths
    end
end
